### ISSUE TITLE
Merging/Branching Brainstorm (db:migrate apply function?)

### ISSUE THREAD

**Issue by kevinc1984** [ruckus/ruckusing-migrations#118]
I'd like to get anyone's general ideas about the feasibility of having merging capabliities built in. For example:

Dev Branch:
Adds migration 1 and 2; commits.

Topic Branch:
Checkout dev branch, up to date with 1 and 2.
Adds migration file 3, does not yet merge back to dev.

Dev Branch:
Adds migration file 4. Commits.

Topic Branch:
Finished work, merges to dev branch.

Develoer in dev branch now has 1, 2, 3, and 4, but since 4 has already been run prior to getting migration file 3, file 3 never runs.

Ideally, it might be nice to be able to see a diff of all migrations that have not run yet, since they will be sprinkled in various places of your migrations folder, and run them either all once or specifically (ex: db::migrate apply=12121220000)

**Comment by kobell** [comment]
You can feel free to close this issue. Thanks.
