### ISSUE TITLE
db:migrate throws exception if migrations dir is not writable

### ISSUE THREAD

**Issue by denodster** [ruckus/ruckusing-migrations#152]
I'm trying to use ruckusing with pagodabox which requires a read only environment.
I want to run db:migration in deployment, however it crashes because the migrations directory is not writiable.

This doesn't make sense to me, why does the migrations dir need to be writable just to migrate the database? the migrations already exist I just need it to read them and migrate the database...

The exception in question is located on Line 335 of Migrate.php

**Comment by ruckus** [comment]
Yes, you're right in that the `db:migrate` task doesn't need write permissions. I dont recall 100% but I think that check was in there for the `db:dump` task, which does write to that directory. And that logic get erroneously carried over. I will look into removing that condition.

**Comment by denodster** [comment]
Fantastic, thanks.
Any idea when this fix will be available via composer?

**Comment by ruckus** [comment]
I've released `1.0.9` with this change. Thanks.
