### ISSUE TITLE
Error during migrations and rollbacks. "Reason: Commands out of sync; you can't run this command now"

### ISSUE THREAD

**Issue by stilliard** [ruckus/ruckusing-migrations#158]
Hi, i'm now getting this error in the latest release when running commands like "$this->drop_table('name');" with a mysql database.
Tested and it was working up till the latest version.

Tested more and found i get this same error if i create a migration and run 2 or more execute statements, e.g. 
```php
<?php

class DemoTest extends Ruckusing_Migration_Base
{
    public function up()
    {
        $this->execute('SELECT VERSION()');
        $this->execute('SELECT VERSION()');
    }//up()

    public function down()
    {
    }//down()
}

```

**Comment by ruckus** [comment]
Is this a recent restriction in MySQL? I think it must be. The MySQL docs have this to say:

https://dev.mysql.com/doc/refman/5.0/en/commands-out-of-sync.html

If you get Commands out of sync; you can't run this command now in your client code, you are calling client functions in the wrong order.

> This can happen, for example, if you are using mysql_use_result() and try to execute a new query before you have called mysql_free_result(). It can also happen if you try to execute two queries that return data without calling mysql_use_result() or mysql_store_result() in between.

Which is pretty crazy. But anyways, it sounds like we need to call `mysql_free_result` in the MySQL adapter right before `execute()` returns.

**Comment by stilliard** [comment]
Looks to be related to the multi_query() calls, I'm working on a patch now to try out calling free result. 
I've added a unit test to check for this in MySQLAdapterTest.php
```php
    public function test_multiple_multi_query_calls()
    {
        $this->adapter->multi_query("SELECT VERSION()");
        $this->adapter->multi_query("SELECT VERSION()");
    }
```

**Comment by stilliard** [comment]
I've just opened a pull request that fixes this :) 
#159
