### ISSUE TITLE
Exception not properly thrown

### ISSUE THREAD

**Issue by Patabugen** [ruckus/ruckusing-migrations#173]
There's a slight syntax error on this line:

https://github.com/ruckus/ruckusing-migrations/blob/master/lib/Ruckusing/Util/Migrator.php#L220

I believe this line:
`"\n\tUnable to create migrations directory at %s, check permissions?", $path,`

Should be this:
`sprintf("\n\tUnable to create migrations directory at %s, check permissions?", $path),`

When my migrations directory is not writeable I get this:

```
Exception.php(51) : Argument 3 passed to Ruckusing_Exception::__construct() must be an instance of Exception, integer given, called in C:\wamp\www\cantheyeat\vendor\ruckusing\ruckusing-migrations\lib\Ruckusing\Util\Migrator.php on line 221
```

**Comment by ruckus** [comment]
Thanks for the heads up!
