### ISSUE TITLE
Documentation for config file

### ISSUE THREAD

**Issue by kardasjan** [ruckus/ruckusing-migrations#176]
I might be just stupid but I am unable to find how to use configuration file and its database definitions. How to switch from development to test is a mystery after walking through the docs.

**Comment by ruckus** [comment]
Sorry about that. I can see how that it was very unclear. 

The answer is via the `ENV` argument. I've added a section to the README

https://github.com/ruckus/ruckusing-migrations/blob/master/README.md#environments
