### ISSUE TITLE
Fatal error: Class 'mysqli' not found in /web/vendor/ruckusing/ruckusing-migrations/lib/Ruckusing/Adapter/MySQL/Base.php on line 1259

### ISSUE THREAD

**Issue by justinmchase** [ruckus/ruckusing-migrations#178]
I can't seem to figure this out. I'm running in an official php docker image and using version `1.1.1` of this library.

Dockerfile:
```
FROM php:5.6-apache

RUN apt-get update && \
    apt-get install -y \
    libxml2 \
    git \
    nodejs \
    openssl \
    php5-memcached \
    php5-mcrypt \
    php5-mysqlnd \
    php5-cli \
    php5-gd \
    php5-intl \
    php5-imagick && \
    apt-get autoremove -y
```

Then when I go into the image and try to run a migration it throws the above error.

```
docker-compose run example ./bin/ruckus.php db:migrate
```

I've also tried restarting apache:
```
$ /etc/init.d/apach2 restart
```

Other details:
```
root@fa1b79b059bc:/web# cat /etc/php5/mods-available/mysqli.ini
; configuration for php MySQL module
; priority=20
extension=mysqli.so
```

```
root@fa1b79b059bc:/web# ls /usr/lib/php5/20131226/
gd.so  imagick.so  intl.so  json.so  mcrypt.so	memcached.so  mysql.so	mysqli.so  mysqlnd.so  opcache.so  pdo.so  pdo_mysql.so  readline.so
```

I've scoured stackoverflow for answers but most of the solution seem to just be to install `php5-mysqlnd` with `apt-get`, which I did yet its still not working.

Any help would be greatly appreciated!

**Comment by justinmchase** [comment]
I sort of got it to work but I don't know why I had to do these things manually. If anyone knew what I'm doing wrong I would love to hear it. 

But the manual steps that solved my problem were to add this to my `Dockerfile`:
```
RUN ln /etc/php5/cli/php.ini /usr/local/etc/php/php.ini
```

And this to my `php.ini` file:
```
extension_dir = /usr/lib/php5/20131226
```

By default the php cli was not loading any ini file according to `php -i | grep ini` and for some reason the extensions appear to be installed in a directory other than where it is looking for extensions by default.

Would love some insight into this issue.

**Comment by ruckus** [comment]
Its been a long time since I have done anything PHP related and it looks like your Ubuntu and from what I can recall the PHP configuration on Ubuntu (as installed via `apt`) is it loads a different PHP INI file whether the runtime environment is under Apache or CLI.

I think thats what you're seeing. 

Either way - this seems to more of an issue with the PHP configuration on your end than issue with the ruckusing migrations library (?)

**Comment by justinmchase** [comment]
Yeah it appears to be just a php 5.6 configuration issue. Thanks.
